service: product-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev

functions:
  main:
    handler: dist/main.handler
    environment:
      DATABASE_URL:
        Fn::GetAtt:
          - Database
          - Endpoint.Address
    events:
      - http:
          method: ANY
          path: '{proxy+}'

resources:
  Resources:
    Database:
      Type: AWS::RDS::DBInstance
      Properties:
        DBName: products
        DBInstanceIdentifier: ${self:service}-${self:provider.stage}
        DBInstanceClass: db.t3.micro
        Engine: postgres
        AllocatedStorage: 1
        MasterUsername: ${DATABASE_USERNAME}
        MasterUserPassword: ${DATABASE_PASSWORD}
        PubliclyAccessible: true
