import fs from 'fs';
// Generated by https://quicktype.io

export interface Manga {
  bib_key:     string;
  info_url:    string;
  preview:     string;
  preview_url: string;
  details:     Details;
}

export interface Details {
  subtitle:            string;
  description:         Created;
  isbn_10:             string[];
  local_id:            string[];
  full_title:          string;
  lc_classifications:  string[];
  key:                 string;
  authors:             Author[];
  languages:           Type[];
  pagination:          string;
  source_records:      string[];
  title:               string;
  dewey_decimal_class: string[];
  notes:               Created;
  number_of_pages:     number;
  isbn_13:             string[];
  edition_name:        string;
  subjects:            string[];
  publish_date:        string;
  publish_country:     string;
  by_statement:        string;
  oclc_numbers:        string[];
  works:               Type[];
  type:                Type;
  latest_revision:     number;
  revision:            number;
  created:             Created;
  last_modified:       Created;
}

export interface Author {
  key:  string;
  name: string;
}

export interface Created {
  type:  string;
  value: string;
}

export interface Type {
  key: string;
}

export const Products = fs.readdirSync('.').map(file => {
  const json = fs.readFileSync(file, {encoding: 'utf8'})
  return JSON.parse(json) as Manga
});
